version: '3.9'
services:
  postgresGallatinWriteDb:
    container_name: postgres_gallatin_write_db_container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admintest
      POSTGRES_USER: admintest
      POSTGRES_DB: gallatin_write 
    ports:
      - 5432:5432
    volumes:
      - ./docker-volumes/postgresql-gallatin:/var/lib/postgresql
  mysqlGallatinReadDb:
    container_name: mysql_gallatin_read_db_container
    image: mysql
    command: --init-file /data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admintest
      MYSQL_DATABASE: gallatin_read
      MYSQL_PASSWORD: admintest
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/data/application/init.sql
      - ./docker-volumes/mysql-auth:/var/lib/mysql
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672