version: '3.9'
services:
  nashville:
    build:
      context: .
      dockerfile: ./apps/nashville/Dockerfile
      target: development
    command: pnpm run start:dev nashville
    ports:
     - '5000:5000'
    volumes:
      - .:/user/src/app
  gallatin:
    build:
      context: .
      dockerfile: ./apps/gallatin/Dockerfile
      target: development
    command: pnpm run start:dev gallatin 
    ports:
     - '3002:3002'
    volumes:
      - .:/user/src/app      
  ashland:
    build:
      context: .
      dockerfile: ./apps/ashland/Dockerfile
      target: development
    command: pnpm run start:dev ashland 
    volumes:
      - .:/user/src/app        
  postgresDb:
    container_name: postgres_db_container
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admintest
      POSTGRES_USER: admintest
      POSTGRES_DB: gallatin_write 
    ports:
      - 5432:5432
    volumes:
      - ./docker-volumes/postgresql-gallatin:/var/lib/postgresql
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    ports:
      - 5672:5672
      - 15672:15672